import { Roboto } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "react-hot-toast";
import BackgroundDots from "@/components/BackgroundDots";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const roboto = Roboto({ subsets: ["latin"], weight: '400' });

export const metadata = {
  title: "Kishor Nishad",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={roboto.className}>
        <BackgroundDots>
          <div className=" relative max-w-[1100px] mx-auto p-2 flex flex-col">
            <Navbar />
            <div className="min-h-[40vh]">
              {children}
            </div>
            <Footer />
          </div>
          <Toaster />
        </BackgroundDots>
      </body>

    </html>
  );
}
